import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { supabase } from '@/integrations/supabase/client';
import type { Database } from '@/integrations/supabase/types';
import { Button } from '@/components/ui/button';
import { Plus } from 'lucide-react';
type Entry = Database['public']['Tables']['finance_entries']['Row'];
const field = 'h-10 w-full border border-input bg-background px-3 text-foreground';
const money = (n: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(n);
export function FinancePanel({ userId, view }: { userId: string; view: 'overview'|'income'|'expense'|'recurring' }) {
 const [rows,setRows] = useState<Entry[]>([]); const [description,setDescription] = useState(''); const [amount,setAmount] = useState(''); const [due,setDue] = useState(''); const [recurring,setRecurring] = useState(''); const [error,setError] = useState('');
 async function load() { const { data, error: e } = await supabase.from('finance_entries').select('*').eq('user_id', userId).order('created_at',{ascending:false}); if(e) setError('Não foi possível carregar os lançamentos.'); else setRows(data ?? []); }
 useEffect(() => { void load(); },[userId]);
 const totals = useMemo(() => ({ received: rows.filter(r => r.direction === 'income' && r.paid_at).reduce((n,r) => n+r.amount,0), receivable: rows.filter(r => r.direction === 'income' && !r.paid_at).reduce((n,r) => n+r.amount,0), paid: rows.filter(r => r.direction === 'expense' && r.paid_at).reduce((n,r) => n+r.amount,0), payable: rows.filter(r => r.direction === 'expense' && !r.paid_at).reduce((n,r) => n+r.amount,0) }),[rows]);
 const shown = rows.filter(r => view === 'overview' || view === 'recurring' && !!r.recurring || view === 'income' && r.direction === 'income' || view === 'expense' && r.direction === 'expense');
 async function add(e: FormEvent) { e.preventDefault(); const { error: err } = await supabase.from('finance_entries').insert({ user_id:userId, direction:view === 'expense' ? 'expense' : 'income', description:description.trim(), amount:Number(amount), due_at:due||null, recurring:recurring || null }); if(err) setError('Não foi possível registrar.'); else { setDescription(''); setAmount(''); setDue(''); setRecurring(''); setError(''); await load(); } }
 return <div className="space-y-7"><div><p className="text-xs uppercase text-accent">Financeiro</p><h1 className="font-display text-4xl uppercase">{({overview:'Visão geral',income:'Entradas',expense:'Saídas',recurring:'Recorrências'})[view]}</h1></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Recebido',totals.received],['A receber',totals.receivable],['Pago',totals.paid],['A pagar',totals.payable]].map(([label,value]) => <div key={label} className="border-t-2 border-primary bg-card p-4"><strong className="font-display text-2xl">{money(Number(value))}</strong><p className="text-sm text-muted-foreground">{label}</p></div>)}</div><p className="text-sm text-muted-foreground">Propostas do CRM não são lançamentos financeiros. Registre os valores aqui quando houver cobrança ou recebimento.</p>
 {view !== 'overview' && <form onSubmit={add} className="grid gap-3 border-y border-border py-5 sm:grid-cols-2"><label className="text-sm">Descrição<input required maxLength={160} value={description} onChange={e => setDescription(e.target.value)} className={field}/></label><label className="text-sm">Valor<input required type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} className={field}/></label><label className="text-sm">Vencimento<input type="date" value={due} onChange={e => setDue(e.target.value)} className={field}/></label><label className="text-sm">Recorrência<select value={recurring} onChange={e => setRecurring(e.target.value)} className={field}><option value="">Avulso</option><option value="monthly">Mensal</option><option value="yearly">Anual</option></select></label><Button className="w-fit" type="submit"><Plus/> Registrar {view === 'expense' ? 'saída' : 'entrada'}</Button></form>}
 {error && <p role="alert" className="text-destructive">{error}</p>}<div className="divide-y divide-border border-y border-border">{shown.map(r => <div key={r.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><strong>{r.description}</strong><p className="text-sm text-muted-foreground">{r.direction === 'income' ? 'Entrada' : 'Saída'} · {r.recurring === 'monthly' ? 'Mensal' : r.recurring === 'yearly' ? 'Anual' : 'Avulso'} · {r.due_at ? `Vence ${new Date(`${r.due_at}T12:00:00`).toLocaleDateString('pt-BR')}` : 'Sem vencimento'}</p></div><div className="flex items-center gap-3"><strong>{money(r.amount)}</strong><Button variant="outline" size="sm" onClick={async () => { await supabase.from('finance_entries').update({ paid_at: r.paid_at ? null : new Date().toISOString().slice(0,10) }).eq('id',r.id); await load(); }}>{r.paid_at ? 'Pago · desfazer' : r.direction === 'income' ? 'Marcar recebido' : 'Marcar pago'}</Button></div></div>)}{!shown.length && <p className="py-8 text-muted-foreground">Nenhum lançamento nesta visão.</p>}</div></div>;
}
