import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";
import { Button } from "@/components/ui/button";
export const Route = createFileRoute("/auth")({ head: () => ({ meta: [{ title: "Entrar | Gerenciador Avançado" }, { name: "description", content: "Acesse sua conta para buscar empresas, acompanhar leads e créditos." }, { property: "og:title", content: "Entrar | Gerenciador Avançado" }, { property: "og:description", content: "Acesse sua conta para buscar empresas, acompanhar leads e créditos." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Auth });
function Auth() {
  const navigate = useNavigate(); const [signup, setSignup] = useState(false); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { supabase.auth.getUser().then(({ data }) => { if (data.user) navigate({ to: "/" }); }); }, [navigate]);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(""); const { data, error } = signup ? await supabase.auth.signUp({ email, password }) : await supabase.auth.signInWithPassword({ email, password }); setBusy(false); if (error) setError(error.message); else if (data.session) navigate({ to: "/" }); else setError("Confira seu e-mail para confirmar a conta antes de entrar."); }
  return <main className="grid min-h-screen place-items-center bg-background px-5"><div className="w-full max-w-md border-t-4 border-primary bg-card p-8"><p className="text-xs uppercase text-accent">Prospecção B2B</p><h1 className="mt-2 font-display text-4xl font-bold uppercase">Gerenciador Avançado</h1><p className="mt-4 text-muted-foreground">{signup ? "Crie sua conta e receba 10 créditos." : "Entre para continuar sua prospecção."}</p><form onSubmit={submit} className="mt-8 space-y-4"><label className="block text-sm">E-mail<input type="email" required value={email} onChange={e => setEmail(e.target.value)} className="mt-1 block h-11 w-full border border-input bg-background px-3"/></label><label className="block text-sm">Senha<input type="password" required minLength={6} value={password} onChange={e => setPassword(e.target.value)} className="mt-1 block h-11 w-full border border-input bg-background px-3"/></label>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={busy} className="w-full">{busy ? "Aguarde…" : signup ? "Criar conta" : "Entrar"}</Button></form><Button variant="outline" className="mt-3 w-full" onClick={async () => { setError(""); const result = await lovable.auth.signInWithOAuth("google", { redirect_uri: window.location.origin }); if (result.error) setError(result.error.message); else if (!result.redirected) navigate({ to: "/" }); }}>Continuar com Google</Button><Button variant="link" className="mt-3 w-full" onClick={() => { setSignup(!signup); setError(""); }}>{signup ? "Já tenho conta" : "Criar conta"}</Button></div></main>;
}
