CREATE TABLE public.accounts (user_id uuid PRIMARY KEY, display_name text NOT NULL DEFAULT '', credits integer NOT NULL DEFAULT 10 CHECK (credits >= 0), notify_email boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.accounts TO authenticated;
GRANT ALL ON public.accounts TO service_role;
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read own account" ON public.accounts FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "create own account" ON public.accounts FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid() AND credits = 10);
CREATE POLICY "edit own preferences" ON public.accounts FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
REVOKE UPDATE (credits) ON public.accounts FROM authenticated;
CREATE TABLE public.searches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, sector text NOT NULL, city text NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','done','failed')), results jsonb NOT NULL DEFAULT '[]'::jsonb, total integer NOT NULL DEFAULT 0, without_site integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.searches TO authenticated;
GRANT ALL ON public.searches TO service_role;
ALTER TABLE public.searches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read own searches" ON public.searches FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE INDEX searches_user_date ON public.searches (user_id, created_at DESC);
CREATE TABLE public.saved_leads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, place_id text NOT NULL, name text NOT NULL, address text NOT NULL DEFAULT '', phone text, website text, email text, rating numeric, reviews integer, maps_url text, sector text, status text NOT NULL DEFAULT 'novo' CHECK (status IN ('novo','contatado','ganho')), contacted_at timestamptz, google_opportunity boolean NOT NULL DEFAULT false, notes text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id, place_id));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.saved_leads TO authenticated;
GRANT ALL ON public.saved_leads TO service_role;
ALTER TABLE public.saved_leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own saved leads" ON public.saved_leads FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE INDEX saved_leads_user ON public.saved_leads (user_id, created_at DESC);
CREATE TABLE public.tickets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, subject text NOT NULL, message text NOT NULL, reply text, status text NOT NULL DEFAULT 'aberto' CHECK (status IN ('aberto','respondido','fechado')), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.tickets TO authenticated;
GRANT ALL ON public.tickets TO service_role;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read own tickets" ON public.tickets FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "create own tickets" ON public.tickets FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid() AND reply IS NULL AND status = 'aberto');
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role text NOT NULL CHECK (role IN ('admin','user')), UNIQUE(user_id, role));
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read own role" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE FUNCTION public.consume_search(p_sector text, p_city text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_id uuid; BEGIN IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Login necessário'; END IF; INSERT INTO public.accounts(user_id) VALUES(auth.uid()) ON CONFLICT (user_id) DO NOTHING; UPDATE public.accounts SET credits = credits - 1 WHERE user_id = auth.uid() AND credits > 0; IF NOT FOUND THEN RAISE EXCEPTION 'Créditos insuficientes'; END IF; INSERT INTO public.searches(user_id, sector, city) VALUES(auth.uid(), left(p_sector,80), left(p_city,80)) RETURNING id INTO v_id; RETURN v_id; END $$;
REVOKE ALL ON FUNCTION public.consume_search(text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.consume_search(text,text) TO authenticated;
CREATE FUNCTION public.finish_search(p_id uuid, p_results jsonb, p_success boolean) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_user uuid; BEGIN SELECT user_id INTO v_user FROM public.searches WHERE id = p_id AND status = 'pending' FOR UPDATE; IF NOT FOUND THEN RETURN; END IF; IF p_success THEN UPDATE public.searches SET status='done', results=p_results, total=jsonb_array_length(p_results), without_site=(SELECT count(*) FROM jsonb_array_elements(p_results) x WHERE x->>'site' IS NULL) WHERE id=p_id; ELSE UPDATE public.searches SET status='failed' WHERE id=p_id; UPDATE public.accounts SET credits=credits+1 WHERE user_id=v_user; END IF; END $$;
REVOKE ALL ON FUNCTION public.finish_search(uuid,jsonb,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.finish_search(uuid,jsonb,boolean) TO service_role;
CREATE FUNCTION public.has_role(_user_id uuid, _role text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
REVOKE ALL ON FUNCTION public.has_role(uuid,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_role(uuid,text) TO authenticated;
CREATE POLICY "admins read tickets" ON public.tickets FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin'));
CREATE POLICY "admins reply tickets" ON public.tickets FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));