ALTER TABLE public.accounts ADD COLUMN auto_crm boolean NOT NULL DEFAULT true;
GRANT UPDATE (auto_crm) ON public.accounts TO authenticated;
ALTER TABLE public.saved_leads ADD COLUMN do_not_contact boolean NOT NULL DEFAULT false;
ALTER TABLE public.saved_leads ADD COLUMN review_needed boolean NOT NULL DEFAULT false;
CREATE TABLE public.pipeline_stages (id text PRIMARY KEY, user_id uuid, label text NOT NULL, sort_order integer NOT NULL, kind text NOT NULL DEFAULT 'open' CHECK (kind IN ('open','won','lost')));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pipeline_stages TO authenticated;
GRANT ALL ON public.pipeline_stages TO service_role;
ALTER TABLE public.pipeline_stages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read shared or own stages" ON public.pipeline_stages FOR SELECT TO authenticated USING (user_id IS NULL OR user_id = auth.uid());
CREATE POLICY "add own stages" ON public.pipeline_stages FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid() AND kind = 'open');
CREATE POLICY "edit own stages" ON public.pipeline_stages FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid() AND kind = 'open');
CREATE POLICY "delete own stages" ON public.pipeline_stages FOR DELETE TO authenticated USING (user_id = auth.uid() AND kind = 'open');
INSERT INTO public.pipeline_stages(id,label,sort_order,kind) VALUES ('new','Novo lead',1,'open'),('qualifying','Em qualificação',2,'open'),('ready','Pronto para abordar',3,'open'),('contacted','Contato realizado',4,'open'),('conversation','Em conversa / reunião',5,'open'),('proposal','Proposta enviada',6,'open'),('negotiation','Negociação',7,'open'),('won','Ganho',8,'won'),('lost','Perdido',9,'lost');
CREATE TABLE public.services (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '', active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.services TO authenticated;
GRANT ALL ON public.services TO service_role;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own services" ON public.services FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE TABLE public.opportunities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, lead_id uuid NOT NULL REFERENCES public.saved_leads(id) ON DELETE CASCADE, service_id uuid REFERENCES public.services(id) ON DELETE SET NULL, title text NOT NULL, stage_id text NOT NULL DEFAULT 'new' REFERENCES public.pipeline_stages(id), proposed_oneoff numeric(12,2), proposed_monthly numeric(12,2), owner_name text, priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('baixa','normal','alta')), next_action text, next_action_at timestamptz, diagnosis text, score integer, confidence text, analysis_status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.opportunities TO authenticated;
GRANT ALL ON public.opportunities TO service_role;
ALTER TABLE public.opportunities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own opportunities" ON public.opportunities FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE UNIQUE INDEX one_open_opportunity_per_lead_service ON public.opportunities (user_id, lead_id, coalesce(service_id::text, 'initial')) WHERE closed_at IS NULL;
CREATE TABLE public.search_leads (user_id uuid NOT NULL, search_id uuid NOT NULL REFERENCES public.searches(id) ON DELETE CASCADE, lead_id uuid NOT NULL REFERENCES public.saved_leads(id) ON DELETE CASCADE, PRIMARY KEY(search_id, lead_id));
GRANT SELECT, INSERT ON public.search_leads TO authenticated;
GRANT ALL ON public.search_leads TO service_role;
ALTER TABLE public.search_leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own search links" ON public.search_leads FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE TABLE public.crm_activities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, opportunity_id uuid NOT NULL REFERENCES public.opportunities(id) ON DELETE CASCADE, kind text NOT NULL CHECK (kind IN ('note','call','message','meeting','task','stage')), detail text NOT NULL, due_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.crm_activities TO authenticated;
GRANT ALL ON public.crm_activities TO service_role;
ALTER TABLE public.crm_activities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own activities" ON public.crm_activities FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE TABLE public.finance_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, opportunity_id uuid REFERENCES public.opportunities(id) ON DELETE SET NULL, direction text NOT NULL CHECK (direction IN ('income','expense')), description text NOT NULL, amount numeric(12,2) NOT NULL CHECK (amount >= 0), due_at date, paid_at date, recurring text CHECK (recurring IN ('monthly','yearly')), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.finance_entries TO authenticated;
GRANT ALL ON public.finance_entries TO service_role;
ALTER TABLE public.finance_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own finance entries" ON public.finance_entries FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE OR REPLACE FUNCTION public.import_search_to_crm(p_search_id uuid, p_place_ids text[] DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_search public.searches; v_item jsonb; v_lead_id uuid; v_created int := 0; v_updated int := 0; v_review int := 0; v_existing boolean; BEGIN IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Login necessário'; END IF; SELECT * INTO v_search FROM public.searches WHERE id = p_search_id AND user_id = auth.uid() AND status = 'done'; IF NOT FOUND THEN RAISE EXCEPTION 'Pesquisa não encontrada'; END IF; FOR v_item IN SELECT value FROM jsonb_array_elements(v_search.results) LOOP IF v_item->>'id' IS NULL OR length(v_item->>'id') < 2 OR (p_place_ids IS NOT NULL AND NOT (v_item->>'id' = ANY(p_place_ids))) THEN CONTINUE; END IF; SELECT id INTO v_lead_id FROM public.saved_leads WHERE user_id=auth.uid() AND place_id=v_item->>'id'; v_existing := FOUND; INSERT INTO public.saved_leads(user_id,place_id,name,address,phone,website,rating,reviews,maps_url,sector,review_needed) VALUES(auth.uid(),v_item->>'id',coalesce(nullif(v_item->>'nome',''),'Sem nome'),coalesce(v_item->>'endereco',''),v_item->>'telefone',v_item->>'site',nullif(v_item->>'nota','')::numeric,nullif(v_item->>'avaliacoes','')::integer,v_item->>'mapsUrl',v_search.sector,coalesce(v_item->>'nome','') = '') ON CONFLICT (user_id,place_id) DO NOTHING RETURNING id INTO v_lead_id; IF v_lead_id IS NULL THEN SELECT id INTO v_lead_id FROM public.saved_leads WHERE user_id=auth.uid() AND place_id=v_item->>'id'; END IF; INSERT INTO public.search_leads(user_id,search_id,lead_id) VALUES(auth.uid(),p_search_id,v_lead_id) ON CONFLICT DO NOTHING; IF NOT EXISTS (SELECT 1 FROM public.opportunities WHERE user_id=auth.uid() AND lead_id=v_lead_id) AND NOT EXISTS (SELECT 1 FROM public.saved_leads WHERE id=v_lead_id AND do_not_contact) THEN INSERT INTO public.opportunities(user_id,lead_id,title,stage_id,diagnosis,analysis_status) VALUES(auth.uid(),v_lead_id,coalesce(nullif(v_item->>'nome',''),'Sem nome') || ' — qualificação inicial','new',CASE WHEN v_item->>'site' IS NULL THEN 'Sem site' ELSE 'Site informado' END,'pending') ON CONFLICT DO NOTHING; v_created := v_created + 1; ELSE v_updated := v_updated + 1; END IF; IF coalesce(v_item->>'nome','') = '' THEN v_review := v_review + 1; END IF; END LOOP; RETURN jsonb_build_object('created',v_created,'updated',v_updated,'review',v_review); END $$;
REVOKE ALL ON FUNCTION public.import_search_to_crm(uuid,text[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.import_search_to_crm(uuid,text[]) TO authenticated;